feat: add AppendBuffer implementation.
adrianbenavides/core-rs pull request #2
Opened 2022-02-01 08:14 UTC by adrianbenavides

**Description:**

Includes support for doing writes, rollbacks and reads over the underlying temp file. The API of this struct has been designed to follow the needs of the AppendService client code (doing writes) and the needs of the AsyncAppend internal code (rollbacks and reads), allowing concurrent use of the same temp file from both the AppendService and AsyncAppend using message passing.

Also, note that the `read` method returns the stream needed by the `Appender`. I had a test in `append_service` setting up a server and testing that the `Appender` can work with the stream returned by the `AppendBuffer`, but since it uses private stuff (like the `Appender` struct) I've deleted it. Where should I put this test? In `append_service_test.rs` to avoid making things public unnecessarily?

It will need some extensions when developing the `AsyncAppend` code (like an explicit flush) but the foundations are there.

**Notes for reviewers:**

There is a [TODO](https://github.com/adrianbenavides/core-rs/compare/adrian/append-buffer?expand=1#diff-d1bb91c8449d6381d2f9db207aa6d56933539b7ef8f737721c5b0f9d300a2dcdR16) related to how to handle temporary files.

2022-02-01 14:45 UTC, jgraettinger requested changes
Thanks. A couple of comments below. Let me know if you'd like to connect / talk through them. I do still think it makes sense to focus on higher-order AppendService implementation, and stub out AppendBuffers as a Vec<u8> or similar for now, but :shrug: 

> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/adrianbenavides/core-rs/2#-:-Mupj0gB9zOPAXUpQ42t:b-xu2o14)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @adrianbenavides and @jgraettinger)

___
*[broker/src/client/append_service.rs, line 23 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/2#-Mupglsa8KGb_QWrC5Xi:-Mupglsb5OSEdHCBfweP:b-i1fuc0) ([raw file](https://github.com/adrianbenavides/core-rs/blob/dcc5ac2450acdb212843eabb7761e6df4f206d70/broker/src/client/append_service.rs#L23)):*
> ```XML
>     }
> 
>     async fn handle_requests(
> ```

I don't believe AppendBuffer needs an async API  -- with the exception of the final dispatch of its content to brokers, all interactions with AppendBuffer are while it's exclusively owned by the caller, and I think synchronous write APIs makes more sense for it (simpler to implement and simpler for the caller).
___
*[broker/src/client/appender.rs, line 121 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/2#-Mupi3-lAZ6PcobmKaLX:-Mupi3-lAZ6PcobmKaLY:bbpaufc) ([raw file](https://github.com/adrianbenavides/core-rs/blob/dcc5ac2450acdb212843eabb7761e6df4f206d70/broker/src/client/appender.rs#L121)):*
> ```XML
> 
> #[derive(Debug)]
> pub struct StreamSection<S>
> ```

Can this be replaced with [AsyncReadExt.take](https://docs.rs/tokio/latest/tokio/io/trait.AsyncReadExt.html#method.take) ?


<!-- Sent from Reviewable.io -->

2022-02-01 16:46 UTC, adrianbenavides commented
> I do still think it makes sense to focus on higher-order AppendService implementation, and stub out AppendBuffers as a Vec or similar for now, but :shrug: 

This is what I tried, but that forced me to have an `Arc<Mutex<Vec<>>>`. I guess I could've continued with the higher level implementation using a channel as a stub... In any case, I think this has been a great exercise to really understand how an AsyncAppend and the Appender are glued together. After this I'll be able to focus 100% on the AppendService.

> I don't believe AppendBuffer needs an async API

True, it should be as easy as replacing the channels to sync variants. 

> Can this be replaced with AsyncReadExt.take?

Absolutely, somehow I couldn't find this method!

2022-02-01 18:56 UTC, adrianbenavides reviewed
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/adrianbenavides/core-rs/2)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @adrianbenavides and @jgraettinger)

___
*[broker/src/client/append_service.rs, line 23 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/2#-Mupglsa8KGb_QWrC5Xi:-Muqd46JA4r5FVf8jir0:b-896fix) ([raw file](https://github.com/adrianbenavides/core-rs/blob/dcc5ac2450acdb212843eabb7761e6df4f206d70/broker/src/client/append_service.rs#L23)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

I don't believe AppendBuffer needs an async API  -- with the exception of the final dispatch of its content to brokers, all interactions with AppendBuffer are while it's exclusively owned by the caller, and I think synchronous write APIs makes more sense for it (simpler to implement and simpler for the caller).
</blockquote></details>

Done.
___
*[broker/src/client/appender.rs, line 121 at r1](https://reviewable.io/reviews/adrianbenavides/core-rs/2#-Mupi3-lAZ6PcobmKaLX:-Muqd5t7800Wy9ih_R_1:b-896fix) ([raw file](https://github.com/adrianbenavides/core-rs/blob/dcc5ac2450acdb212843eabb7761e6df4f206d70/broker/src/client/appender.rs#L121)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

Can this be replaced with [AsyncReadExt.take](https://docs.rs/tokio/latest/tokio/io/trait.AsyncReadExt.html#method.take) ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 06:47 UTC, merged

2022-02-07 06:53 UTC, adrianbenavides commented
Merged as the `AppendBuffer` has been refactored and simplified in https://github.com/adrianbenavides/core-rs/pull/3